export const pagesRoutes = [
  ["v-5e1332e8","/AboutTeam.html",{"title":"关于流沙团队","icon":"info","type":"article","readingTime":{"minutes":2.03,"words":610},"excerpt":"关于流沙团队 你好，我是悦创。也是流沙团队的创始人之一，由我来为你介绍我们团队。流沙团队成立于 2021年11月12日，地点：福建省厦门市（额。。。由于资金问题，工作室待定。。。） 1. LOGO 设计理念 设计日期：2021年10月24日 外形是一股风沙漩涡的形状，象征着强大的力量。又似树的年轮，象征着团队像可以像树木一样茁壮成长，生生不息。 2. 团队理"},["/AboutTeam","/AboutTeam.md"]],
  ["v-8daa1a0e","/",{"title":"主页","icon":"home","type":"home","readingTime":{"minutes":0.69,"words":206},"excerpt":""},["/index.html","/README.md"]],
  ["v-038a8aac","/column.html",{"title":"项目主页","icon":"home","type":"home","readingTime":{"minutes":2.61,"words":782},"excerpt":"这是项目主页的案例。你可以在这里放置你的主体内容。 想要使用此布局，你需要在页面 front matter 中设置 home: true。 配置项的相关说明详见 项目主页配置。"},["/column","/column.md"]],
  ["v-fffb8e28","/guide/",{"title":"主要功能与配置演示","icon":"creative","type":"article","readingTime":{"minutes":0.13,"words":40},"excerpt":"目录 Markdown 展示; 页面展示; 禁用展示; 加密展示;","category":["使用指南"]},["/guide/index.html","/guide/README.md"]],
  ["v-7beb5be1","/posts/article9.html",{"title":"文章 9","icon":"edit","type":"article","readingTime":{"minutes":0.11,"words":33},"excerpt":"文章 9 标题 2 这里是内容。 标题 3 这里是内容。","date":"2022-01-09T00:00:00.000Z","localizedDate":"2022年1月9日","category":["CategoryA","CategoryB"],"tag":["tag A","tag B"]},["/posts/article9","/posts/article9.md"]],
  ["v-03842690","/posts/article/article1.html",{"title":"文章 1","icon":"edit","type":"article","readingTime":{"minutes":0.11,"words":32},"excerpt":"文章 1 标题 2 这里是内容。 标题 3 这里是内容。","date":"2022-01-01T00:00:00.000Z","localizedDate":"2022年1月1日","category":["CategoryA"],"tag":["tag A","tag B"]},["/posts/article/article1","/posts/article/article1.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-03d57386","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"title":"使用指南 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/使用指南/","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/index.html"]],
  ["v-06bbb262","/tag/tag-a/",{"title":"tag A 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/tag-a/index.html"]],
  ["v-3e5b7b84","/category/categorya/",{"title":"CategoryA 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/categorya/index.html"]],
  ["v-06bbb224","/tag/tag-b/",{"title":"tag B 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/tag-b/index.html"]],
  ["v-3e5b7ba3","/category/categoryb/",{"title":"CategoryB 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/categoryb/index.html"]],
]
