<template><h1 id="关于站点的信息" tabindex="-1"><a class="header-anchor" href="#关于站点的信息" aria-hidden="true">#</a> 关于站点的信息</h1>
<h2 id="_1-文件夹或文档" tabindex="-1"><a class="header-anchor" href="#_1-文件夹或文档" aria-hidden="true">#</a> 1. 文件夹或文档</h2>
<table>
<thead>
<tr>
<th>序号</th>
<th>名称</th>
<th>含义</th>
</tr>
</thead>
<tbody>
<tr>
<td>00</td>
<td>一下文件夹或内容都在 docs/zh 文件夹下</td>
<td></td>
</tr>
<tr>
<td>01</td>
<td>.vuepress</td>
<td>配置文件存储的位置</td>
</tr>
<tr>
<td>02</td>
<td>abouteam</td>
<td>关于团队</td>
</tr>
<tr>
<td>03</td>
<td>column</td>
<td>专栏</td>
</tr>
<tr>
<td>04</td>
<td>en</td>
<td>英文站点，文章等内容都放在里面</td>
</tr>
<tr>
<td>05</td>
<td>README.md</td>
<td>网站主页</td>
</tr>
<tr>
<td>07</td>
<td>Technology_of_gossip</td>
<td>技术杂谈</td>
</tr>
<tr>
<td>08</td>
<td>Pay_for_courses</td>
<td>付费课程</td>
</tr>
<tr>
<td>09</td>
<td>Children's_programming</td>
<td>少儿编程</td>
</tr>
<tr>
<td>10</td>
<td>Programming_teaching</td>
<td>编程私教</td>
</tr>
</tbody>
</table>
</template>
