export const data = JSON.parse("{\"key\":\"v-5a1aadce\",\"path\":\"/column/python/base/fiveNamesandtypesofdatavariablesandtypes.html\",\"title\":\"04-数据的名字和种类—变量和类型\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"04-数据的名字和种类—变量和类型\",\"time\":\"2021-11-06T21:26:52.000Z\",\"author\":\"AI悦创\",\"original\":true,\"category\":[\"Python 基础\"],\"tags\":[\"Python 基础\"],\"sticky\":false,\"password\":false,\"article\":true,\"timeline\":true,\"navbar\":true,\"sidebar\":true,\"comment\":true,\"summary\":\"你好，我是悦创。 1. 初探数据种类 在正式开始学习这个小节之前你要明白，现在我们是在学习写程序。那么在写程序之前你要知道程序的作用是什么？ 程序的主要作用是处理数据。 数据的种类有很多，我们在手机和电脑上看到的那些文字、数字、图片、视频、页面样式等等都是数据。这些数据都是由程序来处理并显示到屏幕上的。 虽然数据的种类形形色色，并且有些看起来比较复杂，但是在\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://book.bornforthi.com/column/python/base/fiveNamesandtypesofdatavariablesandtypes.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"流沙团队\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"04-数据的名字和种类—变量和类型\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"AI悦创\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Python 基础\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-11-06T21:26:52.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1. 初探数据种类\",\"slug\":\"_1-初探数据种类\",\"children\":[]},{\"level\":2,\"title\":\"2. 数据类型\",\"slug\":\"_2-数据类型\",\"children\":[]},{\"level\":2,\"title\":\"3. 数值运算\",\"slug\":\"_3-数值运算\",\"children\":[]},{\"level\":2,\"title\":\"4. 比较运算\",\"slug\":\"_4-比较运算\",\"children\":[]},{\"level\":2,\"title\":\"5. 变量和赋值\",\"slug\":\"_5-变量和赋值\",\"children\":[]},{\"level\":2,\"title\":\"6. 变量的好处\",\"slug\":\"_6-变量的好处\",\"children\":[]},{\"level\":2,\"title\":\"7. 用赋值更新变量\",\"slug\":\"_7-用赋值更新变量\",\"children\":[]},{\"level\":2,\"title\":\"8. 变量和数据类型的关系\",\"slug\":\"_8-变量和数据类型的关系\",\"children\":[]},{\"level\":2,\"title\":\"9. 总结\",\"slug\":\"_9-总结\",\"children\":[{\"level\":3,\"title\":\"9.1 数据类型\",\"slug\":\"_9-1-数据类型\",\"children\":[]},{\"level\":3,\"title\":\"9.2 数值运算\",\"slug\":\"_9-2-数值运算\",\"children\":[]},{\"level\":3,\"title\":\"9.3 数值比较\",\"slug\":\"_9-3-数值比较\",\"children\":[]},{\"level\":3,\"title\":\"9.4 变量和赋值\",\"slug\":\"_9-4-变量和赋值\",\"children\":[]},{\"level\":3,\"title\":\"9.5 多语言比较：\",\"slug\":\"_9-5-多语言比较\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.86,\"words\":2957},\"filePathRelative\":\"column/python/base/fiveNamesandtypesofdatavariablesandtypes.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
